name: Unethicalite - Experimental (push)

on:
  push:
    branches:
      - experimental

jobs:
  build:
    name: Build and bootstrap
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Assembling
        run: ./gradlew assemble --console=plain

      - name: Building
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain

      - name: Bootstrap
        run: ./gradlew bootstrapExperimental -x test -x checkstyleMain --console=plain

      - name: Push to hosting
        run: |
          git clone https://github.com/unethicalite/unethicalite-hosting.git
          cp -r ./runelite-client/build/bootstrap/. ./unethicalite-hosting
          cd unethicalite-hosting
          
          git config --global user.email "burakinan1@hotmail.com"
          git config --global user.name "Github Actions"
          git add -A
          git commit -m 'Auto release - Client (Experimental)'
          git push https://buracc:${{ secrets.REPO_PAT }}@github.com/unethicalite/unethicalite-hosting.git master